networks :
    backend :


volumes :
    WP_data:
        name : WP    
    MDB_data:
        name : MDB

services :
  nginx :
    depends_on :
        - wordpress
    build : ./containers/nginx
    ports :
      - "443:443"
    volumes :
        - WP_data:/var/www/wordpress/
    networks :
        - backend
    restart : always

  wordpress :
    container_name: wordpress
    build : ./containers/wordpress
    ports :
        - "9000:9000"
    volumes :
        - WP_data:/var/www/wordpress/
    depends_on :
        - mariadb
    networks :
        - backend
    restart : always
    command: bash -c "/tmp/entry.sh && exec bash"
  mariadb :
    container_name: mariadb
    build : ./containers/mariaDB
    ports :
      - "3306:3306"
    environment :
        USER_NAME_MARIADB : ${USER_NAME_MARIADB}
        PASSWORD_NAME_MARIADB : ${USER_PASSWORD_MARIADB}
    env_file :
    - .env
    volumes :
        - MDB_data:/data/mariadb/
    networks :
        - backend
    restart : always
