services :
  web :
    build : ./nginx
    ports :
        - "8080:8080"

  sql :
      build : ./mariaDB
      ports :
        - "3306:3306"
      environment :
          USER_NAME_MARIADB : ${USER_NAME_MARIADB}
          PASSWORD_NAME_MARIADB : ${USER_PASSWORD_MARIADB}
      env_file :
      - .env
