networks :
    backend :


volumes :
    WP_data:
        name : WP    
    MDB_data:
        name : MDB

services :
  nginx :
    depends_on :
        - wordpress
    build : ./nginx
    ports :
        - "8080:8080"
    volumes :
        - WP_data:/var/www/wordpress/
    networks :
        - backend

  wordpress :
    build : ./wordpress
    ports :
        - "9000:9000"
    volumes :
        - WP_data:/var/www/wordpress/
    depends_on :
        - mariadb
    networks :
        - backend
  mariadb :
    build : ./mariaDB
    ports :
      - "3307:3307"
    environment :
        USER_NAME_MARIADB : ${USER_NAME_MARIADB}
        PASSWORD_NAME_MARIADB : ${USER_PASSWORD_MARIADB}
    env_file :
    - .env
    volumes :
        - MDB_data:/data/mariadb/
    networks :
        - backend
