FROM debian:buster

MAINTAINER JoanBondri

RUN		apt-get update -y \
		&& apt-get install mariadb-server -y \
		&& apt-get install vim -y \
		&& apt-get install wget -y 
#CMD		["mysql_secure_installation;"]
